[package]
name = "revw"
version = "0.1.0"
description = "Git revision warden"
edition = "2021"

[dependencies]
ctrlc = { version = "3.4.5", features = ["termination"] }
git2 = "0.19.0"
nix = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.19"
